<?php

if ( function_exists( "register_field_group" ) ) {
	register_field_group( array(
		'id'         => 'acf_front-page',
		'title'      => 'Front Page',
		'fields'     => array(
			array(
				'key'   => 'field_5446505df8d6c',
				'label' => 'Hero',
				'name'  => '',
				'type'  => 'tab',
			),
			array(
				'key'          => 'field_54465091f8d6f',
				'label'        => 'Related Pages',
				'name'         => 'hero-related_pages-repeater',
				'type'         => 'repeater',
				'required'     => 1,
				'sub_fields'   => array(
					array(
						'key'           => 'field_544e244c27b37',
						'label'         => 'Title',
						'name'          => 'title',
						'type'          => 'text',
						'required'      => 1,
						'column_width'  => '',
						'default_value' => '',
						'placeholder'   => '',
						'prepend'       => '',
						'append'        => '',
						'formatting'    => 'html',
						'maxlength'     => '',
					),
					array(
						'key'          => 'field_544e245927b38',
						'label'        => 'Image',
						'name'         => 'image',
						'type'         => 'image',
						'required'     => 0,
						'column_width' => '',
						'save_format'  => 'object',
						'preview_size' => 'thumbnail',
						'library'      => 'all',
					),
					array(
						'key'          => 'field_544e246527b39',
						'label'        => 'Link',
						'name'         => 'link',
						'type'         => 'page_link',
						'required'     => 1,
						'column_width' => '',
						'post_type'    => array(
							0 => 'page',
						),
						'allow_null'   => 0,
						'multiple'     => 0,
					),
				),
				'row_min'      => 3,
				'row_limit'    => 3,
				'layout'       => 'table',
				'button_label' => 'Add Row',
			),
			array(
				'key'   => 'field_54466f03ece7e',
				'label' => 'About',
				'name'  => '',
				'type'  => 'tab',
			),
			array(
				'key'           => 'field_54466f0fece7f',
				'label'         => 'Headline',
				'name'          => 'about-headline',
				'type'          => 'text',
				'required'      => 1,
				'default_value' => '',
				'placeholder'   => '',
				'prepend'       => '',
				'append'        => '',
				'formatting'    => 'html',
				'maxlength'     => '',
			),
			array(
				'key'           => 'field_54466f21ece80',
				'label'         => 'Description',
				'name'          => 'about-description',
				'type'          => 'wysiwyg',
				'required'      => 1,
				'default_value' => '',
				'toolbar'       => 'full',
				'media_upload'  => 'yes',
			),
			array(
				'key'        => 'field_5447b4511acea',
				'label'      => 'Link',
				'name'       => 'about-link',
				'type'       => 'page_link',
				'required'   => 1,
				'post_type'  => array(
					0 => 'page',
				),
				'allow_null' => 0,
				'multiple'   => 0,
			),
			array(
				'key'          => 'field_54466f39ece81',
				'label'        => 'Image',
				'name'         => 'about-image',
				'type'         => 'image',
				'required'     => 0,
				'save_format'  => 'object',
				'preview_size' => 'thumbnail',
				'library'      => 'all',
			),
		),
		'location'   => array(
			array(
				array(
					'param'    => 'page_template',
					'operator' => '==',
					'value'    => '_templates/_template-front-page.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options'    => array(
			'position'       => 'normal',
			'layout'         => 'default',
			'hide_on_screen' => array(
				0  => 'excerpt',
				1  => 'discussion',
				2  => 'comments',
				3  => 'revisions',
				4  => 'slug',
				5  => 'author',
				6  => 'format',
				7  => 'categories',
				8  => 'tags',
				9  => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	) );
}
