<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_flexible-content',
		'title' => 'Flexible Content',
		'fields' => array (
			array (
				'key' => 'field_5422a3a4a988b',
				'label' => 'Inhaltsblöcke',
				'name' => 'flexible-content',
				'type' => 'flexible_content',
				'layouts' => array (
					array (
						'label' => 'Rasteransicht',
						'name' => 'flexible-content-grid',
						'display' => 'table',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_54250d8f47e0f',
								'label' => 'Rasterbreite',
								'name' => 'flexible-content-grid-size',
								'type' => 'select',
								'instructions' => 'Wählen Sie hier aus, wie breit das Raster werden soll.',
								'column_width' => '',
								'choices' => array (
									'two-columns' => 'Zwei Spalten',
									'three-columns' => 'Drei Spalten',
									'four-columns' => 'Vier Spalten',
								),
								'default_value' => 'three-columns : Drei Spalten',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_5422b3e289a41',
								'label' => 'Rasterelemente',
								'name' => 'flexible-content-grid-entry',
								'type' => 'relationship',
								'column_width' => '',
								'return_format' => 'object',
								'post_type' => array (
									0 => 'post',
									1 => 'page',
									2 => 'produkt',
									3 => 'mitarbeiter',
								),
								'taxonomy' => array (
									0 => 'all',
								),
								'filters' => array (
									0 => 'search',
								),
								'result_elements' => array (
									0 => 'featured_image',
									1 => 'post_type',
									2 => 'post_title',
								),
								'max' => '',
							),
						),
					),
					array (
						'label' => 'Nur Text',
						'name' => 'flexible-content-text',
						'display' => 'table',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_544f6d5cbe9a6',
								'label' => 'Textinhalte',
								'name' => 'flexible-content-text-content',
								'type' => 'wysiwyg',
								'column_width' => '',
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
						),
					),
					array (
						'label' => 'Text mit Bild',
						'name' => 'flexible-content-hybrid',
						'display' => 'table',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_544f6db0be9a8',
								'label' => 'Ausrichtung',
								'name' => 'flexible-content-hybrid-flow',
								'type' => 'select',
								'column_width' => '',
								'choices' => array (
									'left' => 'Linksbündig',
									'right' => 'Rechtsbündig',
								),
								'default_value' => '',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_544f6deabe9a9',
								'label' => 'Bildelement',
								'name' => 'flexible-content-hybrid-img',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'object',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_544f6e15be9aa',
								'label' => 'Textelement',
								'name' => 'flexible-content-hybrid-txt',
								'type' => 'wysiwyg',
								'column_width' => '',
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
						),
					),
					array (
						'label' => 'Text mit Infobox',
						'name' => 'flexible-content-info',
						'display' => 'table',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_5422b45a89a43',
								'label' => 'Textbereich',
								'name' => 'flexible-content-info-main',
								'type' => 'wysiwyg',
								'column_width' => '',
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
							array (
								'key' => 'field_5422b47289a44',
								'label' => 'Infobox',
								'name' => 'flexible-content-info-aside',
								'type' => 'textarea',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'maxlength' => '',
								'rows' => '',
								'formatting' => 'br',
							),
							array (
								'key' => 'field_5422b48b89a45',
								'label' => 'Weiterführender Link',
								'name' => 'flexible-content-info-link',
								'type' => 'page_link',
								'column_width' => '',
								'post_type' => array (
									0 => 'post',
									1 => 'page',
									2 => 'produkt',
								),
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_5422b4b589a46',
								'label' => 'Text weiterführender Link',
								'name' => 'flexible-content-info-link-text',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
					),
					array (
						'label' => 'Aufmacher mit Bild – Groß',
						'name' => 'flexible-content-hero-big',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_5424289508b6a',
								'label' => 'Aufmacher – Headline',
								'name' => 'flexible-content-hero-big-headline',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_542428bc08b6b',
								'label' => 'Aufmacher – Bild',
								'name' => 'flexible-content-hero-big-img',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'object',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_542428d708b6c',
								'label' => 'Aufmacher – Text',
								'name' => 'flexible-content-hero-big-txt',
								'type' => 'wysiwyg',
								'column_width' => '',
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
							array (
								'key' => 'field_542429e908b71',
								'label' => 'Aufmacher – Link',
								'name' => 'flexible-content-hero-big-link',
								'type' => 'page_link',
								'column_width' => '',
								'post_type' => array (
									0 => 'post',
									1 => 'page',
									2 => 'produkt',
								),
								'allow_null' => 0,
								'multiple' => 0,
							),
						),
					),
					array (
						'label' => 'Aufmacher mit Bild – Mittel',
						'name' => 'flexible-content-hero-med',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_54366cae74299',
								'label' => 'Aufmacher-Zeile',
								'name' => 'flexible-content-hero-med-row',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_54366d08eab01',
										'label' => 'Aufmacher – Headline',
										'name' => 'flexible-content-hero-med-headline',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_54366d27eab02',
										'label' => 'Aufmacher – Bild',
										'name' => 'flexible-content-hero-med-img',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'object',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
									array (
										'key' => 'field_54366d43eab03',
										'label' => 'Aufmacher – Text',
										'name' => 'flexible-content-hero-med-txt',
										'type' => 'textarea',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'maxlength' => '',
										'rows' => '',
										'formatting' => 'br',
									),
									array (
										'key' => 'field_54366d59eab04',
										'label' => 'Aufmacher – Link',
										'name' => 'flexible-content-hero-med-link',
										'type' => 'page_link',
										'column_width' => '',
										'post_type' => array (
											0 => 'post',
											1 => 'page',
											2 => 'veranstaltung',
											3 => 'produkt',
											4 => 'jobs',
											5 => 'standorte',
										),
										'allow_null' => 0,
										'multiple' => 0,
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'table',
								'button_label' => 'Neue Zeile.',
							),
						),
					),
				),
				'button_label' => 'Neuer Inhaltsblock.',
				'min' => '',
				'max' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'custom_fields',
				1 => 'discussion',
				2 => 'comments',
				3 => 'format',
				4 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
}
