<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_unternehmensinformationen',
		'title' => 'Unternehmensinformationen',
		'fields' => array (
			array (
				'key' => 'field_538c4ce3a26eb',
				'label' => 'Unternehmensinformationen',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_53353c6bbbef5',
				'label' => 'Firmenbezeichnung',
				'name' => 'firmenbezeichnung',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53353c8abbef6',
				'label' => 'Vertretungsberechtigt',
				'name' => 'vertretungsberechtigt',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53353d3abbefe',
				'label' => 'Strasse Hausnummer',
				'name' => 'strasse_hausnummer',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_533580eb9542d',
				'label' => 'Postleitzahl',
				'name' => 'postleitzahl',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_533580f79542e',
				'label' => 'Ort',
				'name' => 'ort',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_533581019542f',
				'label' => 'Bundesland',
				'name' => 'bundesland',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_533d4fc2eb5b0',
				'label' => 'Land',
				'name' => 'land',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53353ca4bbef7',
				'label' => 'Telefon',
				'name' => 'telefon',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53358187bff62',
				'label' => 'Telefon-Link',
				'name' => 'telefon-link',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53353cc5bbef8',
				'label' => 'Telefax',
				'name' => 'telefax',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5335819bbff63',
				'label' => 'Telefax-Link',
				'name' => 'telefax-link',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53353cccbbef9',
				'label' => 'E-Mail',
				'name' => 'e-mail',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53353cdcbbefa',
				'label' => 'Registereintrag-Art',
				'name' => 'registereintrag-art',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53353cf4bbefb',
				'label' => 'Registergericht',
				'name' => 'registergericht',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53353d00bbefc',
				'label' => 'Registernummer',
				'name' => 'registernummer',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53353d20bbefd',
				'label' => 'UST-ID',
				'name' => 'ust-id',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5347ca170972f',
				'label' => 'Social Media',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5347ca2809730',
				'label' => 'Facebook',
				'name' => 'social-facebook',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5347ca4409731',
				'label' => 'Twitter',
				'name' => 'social-twitter',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5347ca5309732',
				'label' => 'Google+',
				'name' => 'social-google',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53f5f703e70ec',
				'label' => 'Youtube',
				'name' => 'social-youtube',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_538c489263c19',
				'label' => 'Favicons',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_538c48ab63c1a',
				'label' => 'Apple-Touch-Icon',
				'name' => 'apple-touch-icon',
				'type' => 'image',
				'instructions' => 'Quadratische PNG-Datei. Minimum 57x57 Pixel, Maximum 152x152 Pixel.',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_538c495d63c1b',
				'label' => 'Apple-Touch-Startup-Image',
				'name' => 'apple-touch-startup-image',
				'type' => 'image',
				'instructions' => 'PNG-Datei. Minimal 320x460 Pixel, Maximal 2048x1496 Pixel.',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_538c49e763c1c',
				'label' => 'Tile-Color',
				'name' => 'tile-color',
				'type' => 'color_picker',
				'instructions' => 'Hintergrundfarbe für MS-Tile-Icons',
				'default_value' => '',
			),
			array (
				'key' => 'field_538c4a3363c1d',
				'label' => 'Tile-Image',
				'name' => 'tile-image',
				'type' => 'image',
				'instructions' => 'Negativ dargestelltes PNG-Bild. Minium 70x70 Pixel. Maximum 310x310 Pixel.',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_538c4b2e63c1e',
				'label' => 'Favicon PNG',
				'name' => 'favicon-png',
				'type' => 'image',
				'instructions' => 'Quadratisches PNG-Bild. 256 Farben. Minimum 16x16 Pixel. Maximum 32x32 Pixel.',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_538c4be963c1f',
				'label' => 'Favicon GIF',
				'name' => 'favicon-gif',
				'type' => 'image',
				'instructions' => 'Quadratisches GIF-Bild. 256 Farben. Minimum 16x16 Pixel. Maximum 32x32 Pixel.',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_538c4c1363c20',
				'label' => 'Favicon ICO',
				'name' => 'favicon-ico',
				'type' => 'image',
				'instructions' => 'Quadratisches ICO-Bild. 256 Farben. Minimum 16x16 Pixel. Maximum 32x32 Pixel.',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
