<?php

if (function_exists("register_field_group")) {
    register_field_group(array(
        'id'         => 'acf_standorte',
        'title'      => 'Standorte',
        'fields'     => array(
            array(
                'key'           => 'field_5315bba4858c9',
                'label'         => 'Standortname',
                'name'          => 'adresse-name',
                'type'          => 'text',
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'formatting'    => 'html',
                'maxlength'     => '',
            ),
            array(
                'key'           => 'field_5315bbbb858ca',
                'label'         => 'Kurzeschreibung',
                'name'          => 'adresse-beschreibung',
                'type'          => 'textarea',
                'default_value' => '',
                'placeholder'   => '',
                'maxlength'     => '',
                'formatting'    => 'br',
                'rows'          => '',
            ),
            array(
                'key'           => 'field_5315bbde858cc',
                'label'         => 'Straße',
                'name'          => 'adresse-strasse',
                'type'          => 'text',
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'formatting'    => 'html',
                'maxlength'     => '',
            ),
            array(
                'key'           => 'field_5315bbe7858cd',
                'label'         => 'Postleitzahl',
                'name'          => 'adresse-plz',
                'type'          => 'text',
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'formatting'    => 'html',
                'maxlength'     => '',
            ),
            array(
                'key'           => 'field_5315bbf9858ce',
                'label'         => 'Ort',
                'name'          => 'adresse-ort',
                'type'          => 'text',
                'default_value' => '',
                'placeholder'   => '',
                'prepend'       => '',
                'append'        => '',
                'formatting'    => 'html',
                'maxlength'     => '',
            ),
            array(
                'key'           => 'field_5315bc02858cf',
                'label'         => 'Bundesland',
                'name'          => 'adresse-region',
                'type'          => 'select',
                'choices'       => array(
                    'Baden-Württemberg'      => 'Baden-Württemberg',
                    'Bayern'                 => 'Bayern',
                    'Berlin'                 => 'Berlin',
                    'Brandenburg'            => 'Brandenburg',
                    'Bremen'                 => 'Bremen',
                    'Hamburg'                => 'Hamburg',
                    'Hessen'                 => 'Hessen',
                    'Mecklenburg-Vorpommern' => 'Mecklenburg-Vorpommern',
                    'Niedersachsen'          => 'Niedersachsen',
                    'Nordrhein-Westfalen'    => 'Nordrhein-Westfalen',
                    'Rheinland-Pfalz'        => 'Rheinland-Pfalz',
                    'Saarland'               => 'Saarland',
                    'Sachsen'                => 'Sachsen',
                    'Sachsen-Anhalt'         => 'Sachsen-Anhalt',
                    'Schleswig-Holstein'     => 'Schleswig-Holstein',
                    'Thüringen'              => 'Thüringen',
                ),
                'default_value' => '',
                'allow_null'    => 0,
                'multiple'      => 0,
            ),
            array(
                'key'           => 'field_5315bc0b858d0',
                'label'         => 'Land',
                'name'          => 'adresse-land',
                'type'          => 'select',
                'choices'       => array(
                    'Deutschland' => 'Deutschland',
                    'Österreich'  => 'Österreich',
                    'Schweiz'     => 'Schweiz',
                ),
                'default_value' => '',
                'allow_null'    => 0,
                'multiple'      => 0,
            ),
        ),
        'location'   => array(
            array(
                array(
                    'param'    => 'post_type',
                    'operator' => '==',
                    'value'    => 'standort',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options'    => array(
            'position'       => 'normal',
            'layout'         => 'default',
            'hide_on_screen' => array(
                0  => 'permalink',
                1  => 'the_content',
                2  => 'excerpt',
                3  => 'custom_fields',
                4  => 'discussion',
                5  => 'comments',
                6  => 'revisions',
                7  => 'slug',
                8  => 'author',
                9  => 'format',
                10 => 'tags',
                11 => 'send-trackbacks',
            ),
        ),
        'menu_order' => 0,
    ));
}
